### ISSUE TITLE
Exception: call to a member function bindTo() on null

### ISSUE THREAD

**Issue by bastien-phi** [laravel/serializable-closure#32]
- Serializable Closure Version: 1.0.5
- Laravel Version: 8.81.0
- PHP Version: 8.1.1
- Database Driver & Version: postgresql 13

### Description:

I'm having this error

```
[2022-01-27 12:50:19] local.ERROR: Call to a member function bindTo() on null {"userId":1,"exception":"[object] (Error(code: 0): Call to a member function bindTo() on null at /home/vagrant/code/vendor/laravel/serializable-closure/src/Serializers/Native.php:193)
[stacktrace]
#0 [internal function]: Laravel\\SerializableClosure\\Serializers\\Native->__unserialize()
#1 /home/vagrant/code/vendor/laravel/serializable-closure/src/Serializers/Signed.php(86): unserialize()
#2 [internal function]: Laravel\\SerializableClosure\\Serializers\\Signed->__unserialize()
#3 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Bus/DatabaseBatchRepository.php(322): unserialize()
#4 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Bus/DatabaseBatchRepository.php(341): Illuminate\\Bus\\DatabaseBatchRepository->unserialize()
#5 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Bus/DatabaseBatchRepository.php(85): Illuminate\\Bus\\DatabaseBatchRepository->toBatch()
#6 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Bus/DatabaseBatchRepository.php(112): Illuminate\\Bus\\DatabaseBatchRepository->find()
#7 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Bus/PendingBatch.php(255): Illuminate\\Bus\\DatabaseBatchRepository->store()
#8 /home/vagrant/code/app/MyJob.php(51): Illuminate\\Bus\\PendingBatch->dispatch()
```

when trying to dispatch a batch with laravel :

```php
 Bus::batch($jobs)
    ->then($this->synchronizationSucceeded(...))
    ->dispatch();
```

Defined with
```php
 Bus::batch($jobs)
    ->then(fn() => $this->synchronizationSucceeded())
    ->dispatch();
```
everything goes well.

### Steps To Reproduce:

```php
class Test {

    public function test_first_class_callable(): void
    {
        $closure = new SerializableClosure($this->foo(...));

        $serialized = serialize($closure);

        $unserialized = unserialize($serialized); // Error : Call to a member function bindTo() on null
    }

    public function foo()
    {
    }
}
```

**Comment by nunomaduro** [comment]
@bastien-phi Can you give a try to the branch https://github.com/laravel/serializable-closure/pull/33?

**Comment by bastien-phi** [comment]
@nunomaduro Just tried main branch as Taylor merged your PR, everything looks ok.

Thanks !
