### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by AkioSarkiz** [laravel/serializable-closure#51]
- Serializable Octane: 1.2.14
- Laravel Version: 9.19.0
- PHP Version: 8.1.0
- Database Driver & Version: postgres 14

### Description:
I am using octane. And when I start the application, I periodically get such an error in the logs. I can't figure out what it is related to? There is no information about what event is in question. Or maybe about the listeners, the job?
```
Serialization of 'Closure' is not allowed {"userId":1,"exception":"[object] (Exception(code: 0): Serialization of 'Closure' is not allowed at /var/www/api/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:158)
[stacktrace]
#0 /var/www/api/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(158): serialize(Object(Illuminate\\Events\\CallQueuedListener))
#1 /var/www/api/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(127): Illuminate\\Queue\\Queue->createObjectPayload(Object(Illuminate\\Events\\CallQueuedListener), NULL)
#2 /var/www/api/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(105): Illuminate\\Queue\\Queue->createPayloadArray(Object(Illuminate\\Events\\CallQueuedListener), NULL, '')
#3 /var/www/api/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(38): Illuminate\\Queue\\Queue->createPayload(Object(Illuminate\\Events\\CallQueuedListener), NULL, '')
#4 /var/www/api/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(57): Illuminate\\Queue\\SyncQueue->push(Object(Illuminate\\Events\\CallQueuedListener), '', NULL)
#5 /var/www/api/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(591): Illuminate\\Queue\\Queue->pushOn(NULL, Object(Illuminate\\Events\\CallQueuedListener))
#6 /var/www/api/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(515): Illuminate\\Events\\Dispatcher->queueHandler('App\\\\Listeners\\\\F...', 'handle', Array)
#7 /var/www/api/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(441): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}(Object(Laravel\\Octane\\Events\\RequestTerminated))
#8 /var/www/api/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Laravel\\\\Octane\\\\...', Array)
#9 /var/www/api/vendor/laravel/octane/src/DispatchesEvents.php(20): Illuminate\\Events\\Dispatcher->dispatch('Laravel\\\\Octane\\\\...')
#10 /var/www/api/vendor/laravel/octane/src/ApplicationGateway.php(52): Laravel\\Octane\\ApplicationGateway->dispatchEvent(Object(Illuminate\\Foundation\\Application), Object(Laravel\\Octane\\Events\\RequestTerminated))
#11 /var/www/api/vendor/laravel/octane/src/Worker.php(110): Laravel\\Octane\\ApplicationGateway->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\JsonResponse))
#12 /var/www/api/vendor/laravel/octane/bin/swoole-server(118): Laravel\\Octane\\Worker->handle(Object(Illuminate\\Http\\Request), Object(Laravel\\Octane\\RequestContext))
#13 [internal function]: {closure}(Object(Swoole\\Http\\Request), Object(Swoole\\Http\\Response))
#14 /var/www/api/vendor/laravel/octane/bin/swoole-server(164): Swoole\\Server->start()
```

### Steps To Reproduce:
Start Octane server

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
