### ISSUE TITLE
Laravel\SerializableClosure\Exceptions\InvalidSignatureException

### ISSUE THREAD

**Issue by Ign0r3dH4x0r** [laravel/serializable-closure#63]
- Serializable Closure Version: 1.2.2
- Laravel Version:  9.45.1
- PHP Version:  8.1.13
- Database Driver & Version: 10.5.18-MariaDB - MariaDB Server | libmysql - mysqlnd 7.4.33
- Laravel queue driver: database

### Description:

Whenever I dispatch a job, the job instantly gets into failed-jobs table and the exception message is:

```
Laravel\SerializableClosure\Exceptions\InvalidSignatureException: Your serialized closure might have been modified or it's unsafe to be unserialized. in /home/amralab/shein-automation.amralab.com/vendor/laravel/serializable-closure/src/Serializers/Signed.php:83
Stack trace:
#0 [internal function]: Laravel\SerializableClosure\Serializers\Signed->__unserialize(Array)
#1 /home/amralab/shein-automation.amralab.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(97): unserialize('O:16:"App\\Jobs\\...')
#2 /home/amralab/shein-automation.amralab.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(60): Illuminate\Queue\CallQueuedHandler->getCommand(Array)
#3 /home/amralab/shein-automation.amralab.com/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#4 /home/amralab/shein-automation.amralab.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(425): Illuminate\Queue\Jobs\Job->fire()
#5 /home/amralab/shein-automation.amralab.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(375): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions))
#6 /home/amralab/shein-automation.amralab.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(173): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\DatabaseJob), 'database', Object(Illuminate\Queue\WorkerOptions))
#7 /home/amralab/shein-automation.amralab.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(147): Illuminate\Queue\Worker->daemon('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#8 /home/amralab/shein-automation.amralab.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(130): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
#9 /home/amralab/shein-automation.amralab.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#10 /home/amralab/shein-automation.amralab.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#11 /home/amralab/shein-automation.amralab.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#12 /home/amralab/shein-automation.amralab.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#13 /home/amralab/shein-automation.amralab.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#14 /home/amralab/shein-automation.amralab.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#15 /home/amralab/shein-automation.amralab.com/vendor/symfony/console/Command/Command.php(312): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#16 /home/amralab/shein-automation.amralab.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(152): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#17 /home/amralab/shein-automation.amralab.com/vendor/symfony/console/Application.php(1022): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /home/amralab/shein-automation.amralab.com/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /home/amralab/shein-automation.amralab.com/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /home/amralab/shein-automation.amralab.com/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /home/amralab/shein-automation.amralab.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /home/amralab/shein-automation.amralab.com/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 {main}
```

Note: It was all OK and working, so far I remember I just added an eloquent update event listener 

```
 protected static function boot()
    {
        parent::boot();
        /**
         * Write code on Method
         *
         * @return void
         */
        static::updated(queueable(function ($order) {
            send_update($order);
        }));
    }
```

and after adding that, the jobs doesn't work. 

Edit: I have also edited a file inside vendor folder `(laraveldaily/laravel-invoices)`

Point to be noted: All the functionalities except laravel queue works fine. 
Hopefully someone will help me. I will also point this issue in laravel.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
